### ISSUE TITLE
没有登录

### ISSUE THREAD

**Issue by AllMyPrecious** [wildfirechat/organization-platform#2]
自己部署的组织机构服务，在客户端配置后，去点击的时候，提示没有登录，是差了什么配置吗

**Comment by imndx** [comment]
组织结构服务里面，需要配置`im server`的信息，该`im-server`要和客户端所连接的的`im-server`是同一个

https://github.com/wildfirechat/organization-platform/blob/80354a789259ad92afb3bb08c9b3e1bfd0742c61/organization-server/config/application.properties#L43-L45

**Comment by AllMyPrecious** [comment]
目前组织机构只能通过导入的形式生成数据么

**Comment by imndx** [comment]
也可以在组织结构后台，一个一个的创建
